// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_seciton: dynamic(() => import("./HeroSeciton")),
  nimbus_keyboards: dynamic(() => import("./NimbusKeyboards")),
};
